#!/bin/sh

if [ $# -ne 1 ]; then
	echo "Usage: ./ifl file_to_be_compiled.ifl"
	echo "Enter ./ifl [1-3] to compile example 1, 2 or 3"
else
	[ -f game.py ] && rm game/*.py

	if [ $1 -eq 1 ]; then
		python compiler.py examples/ex1.ifl
	elif [ $1 -eq 2 ]; then
		python compiler.py examples/ex2.ifl
	elif [ $1 -eq 3 ]; then
		python compiler.py examples/ex3.ifl
	fi

	[ -f parser.out ] && rm parser.out
	[ -f parsetab.py ] && rm parsetab.py
	[ -f parsetab.pyc ] && rm parsetab.pyc
	rm analyzer/*.pyc
	rm game/*.pyc
	rm generator/*.pyc
	rm parser/*.pyc

	cd game/
	python game.py
fi